/// Syncthing `.stignore` format conversion.
///
/// Key differences from `.gitignore`:
/// - Comments use `//` instead of `#`
/// - No trailing `/` to mark directories; Syncthing matches both files and
///   dirs with the same pattern
/// - Leading `/` anchors to the folder root (same semantics as gitignore)
/// - `**` works the same way
/// - `!` prefix for negation (same)
/// - `(?i)` prefix makes the pattern case-insensitive
/// - `(?d)` prefix means "delete ignored items" (opt-in)
///
/// Reference: https://docs.syncthing.net/users/ignoring.html
use crate::gitignore::PrefixedRule;

// ---------------------------------------------------------------------------
// Rule conversion
// ---------------------------------------------------------------------------

/// Convert a single [`PrefixedRule`] into a Syncthing `.stignore` line.
///
/// Returns `None` for rules that have no meaningful stignore representation.
pub fn prefixed_rule_to_stignore(r: &PrefixedRule) -> Option<String> {
    let prefix = r.relative_dir.to_string_lossy();
    let stripped = r.rule.pattern.trim_start_matches('/');

    // Build the path-prefixed pattern
    let pattern = if prefix.is_empty() {
        stripped.to_string()
    } else {
        format!("{}/{}", prefix, stripped)
    };

    if pattern.is_empty() {
        return None;
    }

    let mut line = String::new();

    // Negation comes first, before any Syncthing modifier flags
    if r.rule.negated {
        line.push('!');
    }

    // Anchor with `/` whenever we have a concrete sub-directory prefix so
    // the rule only matches inside that subtree, not anywhere in the repo.
    if !prefix.is_empty() || r.rule.pattern.starts_with('/') {
        if !line.ends_with('!') {
            // Negation already written; the `/` goes right after it
        }
        line.push('/');
    }

    line.push_str(&pattern);

    // Syncthing does not use trailing `/` for dir-only matching, so we omit it.
    // If you want to restrict to directories only you'd need `(?d)` semantics,
    // but that changes deletion behaviour — we leave that decision to the user.

    Some(line)
}

// ---------------------------------------------------------------------------
// Document-level helpers
// ---------------------------------------------------------------------------

/// Section header emitted at the top of every generated `.stignore`.
const HEADER: &str = "\
// .stignore — auto-generated by gitignore-merge
// DO NOT EDIT: regenerate with `gitignore-merge --format syncthing`
//
// Syncthing ignore pattern reference:
//   https://docs.syncthing.net/users/ignoring.html
";

/// Merge a slice of [`PrefixedRule`]s into a `.stignore` document string.
pub fn merge_to_stignore(rules: &[PrefixedRule]) -> String {
    let body: Vec<String> = rules.iter().filter_map(prefixed_rule_to_stignore).collect();

    if body.is_empty() {
        return format!("{}\n// (no rules found)\n", HEADER);
    }

    format!("{}\n{}\n", HEADER, body.join("\n"))
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;
    use crate::gitignore::{PrefixedRule, Rule};

    fn make_rule(pattern: &str, negated: bool, dir_only: bool, rel: &str) -> PrefixedRule {
        PrefixedRule {
            rule: Rule {
                pattern: pattern.into(),
                negated,
                dir_only,
            },
            relative_dir: PathBuf::from(rel),
        }
    }

    #[test]
    fn simple_pattern_gets_prefixed() {
        let r = make_rule("*.log", false, false, "backend");
        assert_eq!(prefixed_rule_to_stignore(&r).unwrap(), "/backend/*.log");
    }

    #[test]
    fn negation_preserved() {
        let r = make_rule("keep.log", true, false, "backend");
        assert_eq!(prefixed_rule_to_stignore(&r).unwrap(), "!/backend/keep.log");
    }

    #[test]
    fn root_level_rule_no_extra_slash() {
        let r = make_rule("*.tmp", false, false, "");
        // No prefix → no leading slash added
        assert_eq!(prefixed_rule_to_stignore(&r).unwrap(), "*.tmp");
    }

    #[test]
    fn dir_only_trailing_slash_stripped() {
        // gitignore `build/` → stignore `build` (no trailing slash)
        let r = make_rule("build", false, true, "frontend");
        let line = prefixed_rule_to_stignore(&r).unwrap();
        assert!(!line.ends_with('/'), "stignore lines must not end with '/'");
    }

    #[test]
    fn already_anchored_pattern() {
        // gitignore `/dist` inside `apps/web` → `/apps/web/dist`
        let r = make_rule("/dist", false, false, "apps/web");
        assert_eq!(prefixed_rule_to_stignore(&r).unwrap(), "/apps/web/dist");
    }

    #[test]
    fn double_star_preserved() {
        let r = make_rule("**/node_modules", false, false, "packages/ui");
        assert_eq!(
            prefixed_rule_to_stignore(&r).unwrap(),
            "/packages/ui/**/node_modules"
        );
    }
}
